<?php

namespace Hrms\Bundle\EmployeeBundle\Controller;

/**
 * This code has been auto-generated by the JMSDiExtraBundle.
 *
 * Manual changes to it will be lost.
 */
class HrmCompanyController__JMSInjector
{
    public static function inject($container) {
        $instance = new \Hrms\Bundle\EmployeeBundle\Controller\HrmCompanyController();
        return $instance;
    }
}
