<?php

namespace Proxies\__CG__\Hrms\Bundle\EmployeeBundle\Entity;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class HrmCompany extends \Hrms\Bundle\EmployeeBundle\Entity\HrmCompany implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    /** @private */
    public function __load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;

            if (method_exists($this, "__wakeup")) {
                // call this after __isInitialized__to avoid infinite recursion
                // but before loading to emulate what ClassMetadata::newInstance()
                // provides.
                $this->__wakeup();
            }

            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }

    /** @private */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    
    public function setIdCompany($idCompany)
    {
        $this->__load();
        return parent::setIdCompany($idCompany);
    }

    public function getIdCompany()
    {
        $this->__load();
        return parent::getIdCompany();
    }

    public function setIdAdmin($idAdmin)
    {
        $this->__load();
        return parent::setIdAdmin($idAdmin);
    }

    public function getIdAdmin()
    {
        $this->__load();
        return parent::getIdAdmin();
    }

    public function setCompanyName($companyName)
    {
        $this->__load();
        return parent::setCompanyName($companyName);
    }

    public function getCompanyName()
    {
        $this->__load();
        return parent::getCompanyName();
    }

    public function setCompanyInfo($companyInfo)
    {
        $this->__load();
        return parent::setCompanyInfo($companyInfo);
    }

    public function getCompanyInfo()
    {
        $this->__load();
        return parent::getCompanyInfo();
    }

    public function setDisplayname($displayname)
    {
        $this->__load();
        return parent::setDisplayname($displayname);
    }

    public function getDisplayname()
    {
        $this->__load();
        return parent::getDisplayname();
    }

    public function setEmailId($emailId)
    {
        $this->__load();
        return parent::setEmailId($emailId);
    }

    public function getEmailId()
    {
        $this->__load();
        return parent::getEmailId();
    }

    public function setPassword($password)
    {
        $this->__load();
        return parent::setPassword($password);
    }

    public function getPassword()
    {
        $this->__load();
        return parent::getPassword();
    }

    public function setRePassword($rePassword)
    {
        $this->__load();
        return parent::setRePassword($rePassword);
    }

    public function getRePassword()
    {
        $this->__load();
        return parent::getRePassword();
    }

    public function setRole($role)
    {
        $this->__load();
        return parent::setRole($role);
    }

    public function getRole()
    {
        $this->__load();
        return parent::getRole();
    }

    public function setAddress($address)
    {
        $this->__load();
        return parent::setAddress($address);
    }

    public function getAddress()
    {
        $this->__load();
        return parent::getAddress();
    }

    public function setTaxId($taxId)
    {
        $this->__load();
        return parent::setTaxId($taxId);
    }

    public function getTaxId()
    {
        $this->__load();
        return parent::getTaxId();
    }

    public function setTwitterId($twitterId)
    {
        $this->__load();
        return parent::setTwitterId($twitterId);
    }

    public function getTwitterId()
    {
        $this->__load();
        return parent::getTwitterId();
    }

    public function setFacebookId($facebookId)
    {
        $this->__load();
        return parent::setFacebookId($facebookId);
    }

    public function getFacebookId()
    {
        $this->__load();
        return parent::getFacebookId();
    }

    public function setLinkedinId($linkedinId)
    {
        $this->__load();
        return parent::setLinkedinId($linkedinId);
    }

    public function getLinkedinId()
    {
        $this->__load();
        return parent::getLinkedinId();
    }

    public function setLogo($logo)
    {
        $this->__load();
        return parent::setLogo($logo);
    }

    public function getLogo()
    {
        $this->__load();
        return parent::getLogo();
    }

    public function setLanguage($language)
    {
        $this->__load();
        return parent::setLanguage($language);
    }

    public function getLanguage()
    {
        $this->__load();
        return parent::getLanguage();
    }

    public function setCurrency($currency)
    {
        $this->__load();
        return parent::setCurrency($currency);
    }

    public function getCurrency()
    {
        $this->__load();
        return parent::getCurrency();
    }

    public function setTimezone($timezone)
    {
        $this->__load();
        return parent::setTimezone($timezone);
    }

    public function getTimezone()
    {
        $this->__load();
        return parent::getTimezone();
    }

    public function setAddDate($addDate)
    {
        $this->__load();
        return parent::setAddDate($addDate);
    }

    public function getAddDate()
    {
        $this->__load();
        return parent::getAddDate();
    }

    public function setLastLogin($lastLogin)
    {
        $this->__load();
        return parent::setLastLogin($lastLogin);
    }

    public function getLastLogin()
    {
        $this->__load();
        return parent::getLastLogin();
    }

    public function setIsactive($isactive)
    {
        $this->__load();
        return parent::setIsactive($isactive);
    }

    public function getIsactive()
    {
        $this->__load();
        return parent::getIsactive();
    }

    public function setIp($ip)
    {
        $this->__load();
        return parent::setIp($ip);
    }

    public function getIp()
    {
        $this->__load();
        return parent::getIp();
    }

    public function getIdUserdetails()
    {
        if ($this->__isInitialized__ === false) {
            return (int) $this->_identifier["idUserdetails"];
        }
        $this->__load();
        return parent::getIdUserdetails();
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'idCompany', 'idAdmin', 'companyName', 'companyInfo', 'displayname', 'emailId', 'password', 'rePassword', 'role', 'address', 'taxId', 'twitterId', 'facebookId', 'linkedinId', 'logo', 'language', 'currency', 'timezone', 'addDate', 'lastLogin', 'isactive', 'ip', 'idUserdetails');
    }

    public function __clone()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            $class = $this->_entityPersister->getClassMetadata();
            $original = $this->_entityPersister->load($this->_identifier);
            if ($original === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            foreach ($class->reflFields as $field => $reflProperty) {
                $reflProperty->setValue($this, $reflProperty->getValue($original));
            }
            unset($this->_entityPersister, $this->_identifier);
        }
        
    }
}