<?php

namespace Proxies\__CG__\Hrms\Bundle\EmployeeBundle\Entity;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class HrmCity extends \Hrms\Bundle\EmployeeBundle\Entity\HrmCity implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    /** @private */
    public function __load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;

            if (method_exists($this, "__wakeup")) {
                // call this after __isInitialized__to avoid infinite recursion
                // but before loading to emulate what ClassMetadata::newInstance()
                // provides.
                $this->__wakeup();
            }

            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }

    /** @private */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    
    public function setCityName($cityName)
    {
        $this->__load();
        return parent::setCityName($cityName);
    }

    public function getCityName()
    {
        $this->__load();
        return parent::getCityName();
    }

    public function setCityCode($cityCode)
    {
        $this->__load();
        return parent::setCityCode($cityCode);
    }

    public function getCityCode()
    {
        $this->__load();
        return parent::getCityCode();
    }

    public function setIdState($idState)
    {
        $this->__load();
        return parent::setIdState($idState);
    }

    public function getIdState()
    {
        $this->__load();
        return parent::getIdState();
    }

    public function getIdCity()
    {
        if ($this->__isInitialized__ === false) {
            return (int) $this->_identifier["idCity"];
        }
        $this->__load();
        return parent::getIdCity();
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'cityName', 'cityCode', 'idState', 'idCity');
    }

    public function __clone()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            $class = $this->_entityPersister->getClassMetadata();
            $original = $this->_entityPersister->load($this->_identifier);
            if ($original === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            foreach ($class->reflFields as $field => $reflProperty) {
                $reflProperty->setValue($this, $reflProperty->getValue($original));
            }
            unset($this->_entityPersister, $this->_identifier);
        }
        
    }
}