<?php

namespace Proxies\__CG__\Hrms\Bundle\EmployeeBundle\Entity;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class HrmModules extends \Hrms\Bundle\EmployeeBundle\Entity\HrmModules implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    /** @private */
    public function __load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;

            if (method_exists($this, "__wakeup")) {
                // call this after __isInitialized__to avoid infinite recursion
                // but before loading to emulate what ClassMetadata::newInstance()
                // provides.
                $this->__wakeup();
            }

            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }

    /** @private */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    
    public function setModuleName($moduleName)
    {
        $this->__load();
        return parent::setModuleName($moduleName);
    }

    public function getModuleName()
    {
        $this->__load();
        return parent::getModuleName();
    }

    public function setModuleValue($moduleValue)
    {
        $this->__load();
        return parent::setModuleValue($moduleValue);
    }

    public function getModuleValue()
    {
        $this->__load();
        return parent::getModuleValue();
    }

    public function setIsactive($isactive)
    {
        $this->__load();
        return parent::setIsactive($isactive);
    }

    public function getIsactive()
    {
        $this->__load();
        return parent::getIsactive();
    }

    public function setCreateDate($createDate)
    {
        $this->__load();
        return parent::setCreateDate($createDate);
    }

    public function getCreateDate()
    {
        $this->__load();
        return parent::getCreateDate();
    }

    public function setOrderby($orderby)
    {
        $this->__load();
        return parent::setOrderby($orderby);
    }

    public function getOrderby()
    {
        $this->__load();
        return parent::getOrderby();
    }

    public function getIdModules()
    {
        if ($this->__isInitialized__ === false) {
            return (int) $this->_identifier["idModules"];
        }
        $this->__load();
        return parent::getIdModules();
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'moduleName', 'moduleValue', 'isactive', 'createDate', 'orderby', 'idModules');
    }

    public function __clone()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            $class = $this->_entityPersister->getClassMetadata();
            $original = $this->_entityPersister->load($this->_identifier);
            if ($original === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            foreach ($class->reflFields as $field => $reflProperty) {
                $reflProperty->setValue($this, $reflProperty->getValue($original));
            }
            unset($this->_entityPersister, $this->_identifier);
        }
        
    }
}