<?php

namespace Proxies\__CG__\Hrms\Bundle\EmployeeBundle\Entity;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class HrmRoles extends \Hrms\Bundle\EmployeeBundle\Entity\HrmRoles implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    /** @private */
    public function __load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;

            if (method_exists($this, "__wakeup")) {
                // call this after __isInitialized__to avoid infinite recursion
                // but before loading to emulate what ClassMetadata::newInstance()
                // provides.
                $this->__wakeup();
            }

            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }

    /** @private */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    
    public function setRoleName($roleName)
    {
        $this->__load();
        return parent::setRoleName($roleName);
    }

    public function getRoleName()
    {
        $this->__load();
        return parent::getRoleName();
    }

    public function setRoleDescription($roleDescription)
    {
        $this->__load();
        return parent::setRoleDescription($roleDescription);
    }

    public function getRoleDescription()
    {
        $this->__load();
        return parent::getRoleDescription();
    }

    public function setCreateDate($createDate)
    {
        $this->__load();
        return parent::setCreateDate($createDate);
    }

    public function getCreateDate()
    {
        $this->__load();
        return parent::getCreateDate();
    }

    public function getIdRoles()
    {
        if ($this->__isInitialized__ === false) {
            return (int) $this->_identifier["idRoles"];
        }
        $this->__load();
        return parent::getIdRoles();
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'roleName', 'roleDescription', 'createDate', 'idRoles');
    }

    public function __clone()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            $class = $this->_entityPersister->getClassMetadata();
            $original = $this->_entityPersister->load($this->_identifier);
            if ($original === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            foreach ($class->reflFields as $field => $reflProperty) {
                $reflProperty->setValue($this, $reflProperty->getValue($original));
            }
            unset($this->_entityPersister, $this->_identifier);
        }
        
    }
}