<?php

namespace Proxies\__CG__\Hrms\Bundle\EmployeeBundle\Entity;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class HrmRolefeatures extends \Hrms\Bundle\EmployeeBundle\Entity\HrmRolefeatures implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    /** @private */
    public function __load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;

            if (method_exists($this, "__wakeup")) {
                // call this after __isInitialized__to avoid infinite recursion
                // but before loading to emulate what ClassMetadata::newInstance()
                // provides.
                $this->__wakeup();
            }

            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }

    /** @private */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    
    public function setIdModules($idModules)
    {
        $this->__load();
        return parent::setIdModules($idModules);
    }

    public function getIdModules()
    {
        $this->__load();
        return parent::getIdModules();
    }

    public function setIdModulefeatures($idModulefeatures)
    {
        $this->__load();
        return parent::setIdModulefeatures($idModulefeatures);
    }

    public function getIdModulefeatures()
    {
        $this->__load();
        return parent::getIdModulefeatures();
    }

    public function setIdRoles($idRoles)
    {
        $this->__load();
        return parent::setIdRoles($idRoles);
    }

    public function getIdRoles()
    {
        $this->__load();
        return parent::getIdRoles();
    }

    public function setIsvisible($isvisible)
    {
        $this->__load();
        return parent::setIsvisible($isvisible);
    }

    public function getIsvisible()
    {
        $this->__load();
        return parent::getIsvisible();
    }

    public function setId1($id1)
    {
        $this->__load();
        return parent::setId1($id1);
    }

    public function getId1()
    {
        $this->__load();
        return parent::getId1();
    }

    public function setIsvisible1($isvisible1)
    {
        $this->__load();
        return parent::setIsvisible1($isvisible1);
    }

    public function getIsvisible1()
    {
        $this->__load();
        return parent::getIsvisible1();
    }

    public function getIdRolefeatures()
    {
        if ($this->__isInitialized__ === false) {
            return (int) $this->_identifier["idRolefeatures"];
        }
        $this->__load();
        return parent::getIdRolefeatures();
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'idModules', 'idModulefeatures', 'idRoles', 'isvisible', 'id1', 'isvisible1', 'idRolefeatures');
    }

    public function __clone()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            $class = $this->_entityPersister->getClassMetadata();
            $original = $this->_entityPersister->load($this->_identifier);
            if ($original === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            foreach ($class->reflFields as $field => $reflProperty) {
                $reflProperty->setValue($this, $reflProperty->getValue($original));
            }
            unset($this->_entityPersister, $this->_identifier);
        }
        
    }
}