<?php

namespace Proxies\__CG__\Hrms\Bundle\EmployeeBundle\Entity;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class HrmTasks extends \Hrms\Bundle\EmployeeBundle\Entity\HrmTasks implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    /** @private */
    public function __load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;

            if (method_exists($this, "__wakeup")) {
                // call this after __isInitialized__to avoid infinite recursion
                // but before loading to emulate what ClassMetadata::newInstance()
                // provides.
                $this->__wakeup();
            }

            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }

    /** @private */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    
    public function setTaskName($taskName)
    {
        $this->__load();
        return parent::setTaskName($taskName);
    }

    public function getTaskName()
    {
        $this->__load();
        return parent::getTaskName();
    }

    public function setTaskDescription($taskDescription)
    {
        $this->__load();
        return parent::setTaskDescription($taskDescription);
    }

    public function getTaskDescription()
    {
        $this->__load();
        return parent::getTaskDescription();
    }

    public function setIdEmployee($idEmployee)
    {
        $this->__load();
        return parent::setIdEmployee($idEmployee);
    }

    public function getIdEmployee()
    {
        $this->__load();
        return parent::getIdEmployee();
    }

    public function setTaskDate($taskDate)
    {
        $this->__load();
        return parent::setTaskDate($taskDate);
    }

    public function getTaskDate()
    {
        $this->__load();
        return parent::getTaskDate();
    }

    public function setModifiedDate($modifiedDate)
    {
        $this->__load();
        return parent::setModifiedDate($modifiedDate);
    }

    public function getModifiedDate()
    {
        $this->__load();
        return parent::getModifiedDate();
    }

    public function getIdTasks()
    {
        if ($this->__isInitialized__ === false) {
            return (int) $this->_identifier["idTasks"];
        }
        $this->__load();
        return parent::getIdTasks();
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'taskName', 'taskDescription', 'idEmployee', 'taskDate', 'modifiedDate', 'idTasks');
    }

    public function __clone()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            $class = $this->_entityPersister->getClassMetadata();
            $original = $this->_entityPersister->load($this->_identifier);
            if ($original === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            foreach ($class->reflFields as $field => $reflProperty) {
                $reflProperty->setValue($this, $reflProperty->getValue($original));
            }
            unset($this->_entityPersister, $this->_identifier);
        }
        
    }
}