<?php

namespace Proxies\__CG__\Hrms\Bundle\EmployeeBundle\Entity;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class HrmMessage extends \Hrms\Bundle\EmployeeBundle\Entity\HrmMessage implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    /** @private */
    public function __load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;

            if (method_exists($this, "__wakeup")) {
                // call this after __isInitialized__to avoid infinite recursion
                // but before loading to emulate what ClassMetadata::newInstance()
                // provides.
                $this->__wakeup();
            }

            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }

    /** @private */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    
    public function setLangCode($langCode)
    {
        $this->__load();
        return parent::setLangCode($langCode);
    }

    public function getLangCode()
    {
        $this->__load();
        return parent::getLangCode();
    }

    public function setKeyName($keyName)
    {
        $this->__load();
        return parent::setKeyName($keyName);
    }

    public function getKeyName()
    {
        $this->__load();
        return parent::getKeyName();
    }

    public function setKeyValue($keyValue)
    {
        $this->__load();
        return parent::setKeyValue($keyValue);
    }

    public function getKeyValue()
    {
        $this->__load();
        return parent::getKeyValue();
    }

    public function getIdMessage()
    {
        if ($this->__isInitialized__ === false) {
            return (int) $this->_identifier["idMessage"];
        }
        $this->__load();
        return parent::getIdMessage();
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'langCode', 'keyName', 'keyValue', 'idMessage');
    }

    public function __clone()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            $class = $this->_entityPersister->getClassMetadata();
            $original = $this->_entityPersister->load($this->_identifier);
            if ($original === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            foreach ($class->reflFields as $field => $reflProperty) {
                $reflProperty->setValue($this, $reflProperty->getValue($original));
            }
            unset($this->_entityPersister, $this->_identifier);
        }
        
    }
}