<?php

namespace Proxies\__CG__\Hrms\Bundle\EmployeeBundle\Entity;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class HrmModulefeatures extends \Hrms\Bundle\EmployeeBundle\Entity\HrmModulefeatures implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    /** @private */
    public function __load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;

            if (method_exists($this, "__wakeup")) {
                // call this after __isInitialized__to avoid infinite recursion
                // but before loading to emulate what ClassMetadata::newInstance()
                // provides.
                $this->__wakeup();
            }

            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }

    /** @private */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    
    public function setFeaturesName($featuresName)
    {
        $this->__load();
        return parent::setFeaturesName($featuresName);
    }

    public function getFeaturesName()
    {
        $this->__load();
        return parent::getFeaturesName();
    }

    public function setFeaturesValue($featuresValue)
    {
        $this->__load();
        return parent::setFeaturesValue($featuresValue);
    }

    public function getFeaturesValue()
    {
        $this->__load();
        return parent::getFeaturesValue();
    }

    public function setIdModules($idModules)
    {
        $this->__load();
        return parent::setIdModules($idModules);
    }

    public function getIdModules()
    {
        $this->__load();
        return parent::getIdModules();
    }

    public function setIswriteaccess($iswriteaccess)
    {
        $this->__load();
        return parent::setIswriteaccess($iswriteaccess);
    }

    public function getIswriteaccess()
    {
        $this->__load();
        return parent::getIswriteaccess();
    }

    public function setCreateDate($createDate)
    {
        $this->__load();
        return parent::setCreateDate($createDate);
    }

    public function getCreateDate()
    {
        $this->__load();
        return parent::getCreateDate();
    }

    public function getIdModulefeatures()
    {
        if ($this->__isInitialized__ === false) {
            return (int) $this->_identifier["idModulefeatures"];
        }
        $this->__load();
        return parent::getIdModulefeatures();
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'featuresName', 'featuresValue', 'idModules', 'iswriteaccess', 'createDate', 'idModulefeatures');
    }

    public function __clone()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            $class = $this->_entityPersister->getClassMetadata();
            $original = $this->_entityPersister->load($this->_identifier);
            if ($original === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            foreach ($class->reflFields as $field => $reflProperty) {
                $reflProperty->setValue($this, $reflProperty->getValue($original));
            }
            unset($this->_entityPersister, $this->_identifier);
        }
        
    }
}