<?php

namespace Proxies\__CG__\Hrms\Bundle\EmployeeBundle\Entity;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class HrmEmployeeproperties extends \Hrms\Bundle\EmployeeBundle\Entity\HrmEmployeeproperties implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    /** @private */
    public function __load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;

            if (method_exists($this, "__wakeup")) {
                // call this after __isInitialized__to avoid infinite recursion
                // but before loading to emulate what ClassMetadata::newInstance()
                // provides.
                $this->__wakeup();
            }

            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }

    /** @private */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    
    public function setPropertyName($propertyName)
    {
        $this->__load();
        return parent::setPropertyName($propertyName);
    }

    public function getPropertyName()
    {
        $this->__load();
        return parent::getPropertyName();
    }

    public function setSerialNo($serialNo)
    {
        $this->__load();
        return parent::setSerialNo($serialNo);
    }

    public function getSerialNo()
    {
        $this->__load();
        return parent::getSerialNo();
    }

    public function setNoOfItems($noOfItems)
    {
        $this->__load();
        return parent::setNoOfItems($noOfItems);
    }

    public function getNoOfItems()
    {
        $this->__load();
        return parent::getNoOfItems();
    }

    public function setNotes($notes)
    {
        $this->__load();
        return parent::setNotes($notes);
    }

    public function getNotes()
    {
        $this->__load();
        return parent::getNotes();
    }

    public function setAddDate($addDate)
    {
        $this->__load();
        return parent::setAddDate($addDate);
    }

    public function getAddDate()
    {
        $this->__load();
        return parent::getAddDate();
    }

    public function setIp($ip)
    {
        $this->__load();
        return parent::setIp($ip);
    }

    public function getIp()
    {
        $this->__load();
        return parent::getIp();
    }

    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int) $this->_identifier["id"];
        }
        $this->__load();
        return parent::getId();
    }

    public function setPropertyType(\Hrms\Bundle\EmployeeBundle\Entity\HrmPropertytype $propertyType = NULL)
    {
        $this->__load();
        return parent::setPropertyType($propertyType);
    }

    public function getPropertyType()
    {
        $this->__load();
        return parent::getPropertyType();
    }

    public function setEmployee(\Hrms\Bundle\EmployeeBundle\Entity\HrmEmployee $employee = NULL)
    {
        $this->__load();
        return parent::setEmployee($employee);
    }

    public function getEmployee()
    {
        $this->__load();
        return parent::getEmployee();
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'propertyName', 'serialNo', 'noOfItems', 'notes', 'addDate', 'ip', 'id', 'propertyType', 'employee');
    }

    public function __clone()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            $class = $this->_entityPersister->getClassMetadata();
            $original = $this->_entityPersister->load($this->_identifier);
            if ($original === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            foreach ($class->reflFields as $field => $reflProperty) {
                $reflProperty->setValue($this, $reflProperty->getValue($original));
            }
            unset($this->_entityPersister, $this->_identifier);
        }
        
    }
}