<?php

namespace Proxies\__CG__\Hrms\Bundle\EmployeeBundle\Entity;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class HrmRolefeatures extends \Hrms\Bundle\EmployeeBundle\Entity\HrmRolefeatures implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    /** @private */
    public function __load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;

            if (method_exists($this, "__wakeup")) {
                // call this after __isInitialized__to avoid infinite recursion
                // but before loading to emulate what ClassMetadata::newInstance()
                // provides.
                $this->__wakeup();
            }

            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }

    /** @private */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    
    public function setIsvisible($isvisible)
    {
        $this->__load();
        return parent::setIsvisible($isvisible);
    }

    public function getIsvisible()
    {
        $this->__load();
        return parent::getIsvisible();
    }

    public function setId1($id1)
    {
        $this->__load();
        return parent::setId1($id1);
    }

    public function getId1()
    {
        $this->__load();
        return parent::getId1();
    }

    public function setIsvisible1($isvisible1)
    {
        $this->__load();
        return parent::setIsvisible1($isvisible1);
    }

    public function getIsvisible1()
    {
        $this->__load();
        return parent::getIsvisible1();
    }

    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int) $this->_identifier["id"];
        }
        $this->__load();
        return parent::getId();
    }

    public function setModulefeatures(\Hrms\Bundle\EmployeeBundle\Entity\HrmModulefeatures $modulefeatures = NULL)
    {
        $this->__load();
        return parent::setModulefeatures($modulefeatures);
    }

    public function getModulefeatures()
    {
        $this->__load();
        return parent::getModulefeatures();
    }

    public function setModules(\Hrms\Bundle\EmployeeBundle\Entity\HrmModules $modules = NULL)
    {
        $this->__load();
        return parent::setModules($modules);
    }

    public function getModules()
    {
        $this->__load();
        return parent::getModules();
    }

    public function setRoles(\Hrms\Bundle\EmployeeBundle\Entity\HrmRoles $roles = NULL)
    {
        $this->__load();
        return parent::setRoles($roles);
    }

    public function getRoles()
    {
        $this->__load();
        return parent::getRoles();
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'isvisible', 'id1', 'isvisible1', 'id', 'modulefeatures', 'modules', 'roles');
    }

    public function __clone()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            $class = $this->_entityPersister->getClassMetadata();
            $original = $this->_entityPersister->load($this->_identifier);
            if ($original === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            foreach ($class->reflFields as $field => $reflProperty) {
                $reflProperty->setValue($this, $reflProperty->getValue($original));
            }
            unset($this->_entityPersister, $this->_identifier);
        }
        
    }
}