<?php

namespace Proxies\__CG__\Hrms\Bundle\EmployeeBundle\Entity;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class HrmAgegroup extends \Hrms\Bundle\EmployeeBundle\Entity\HrmAgegroup implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    /** @private */
    public function __load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;

            if (method_exists($this, "__wakeup")) {
                // call this after __isInitialized__to avoid infinite recursion
                // but before loading to emulate what ClassMetadata::newInstance()
                // provides.
                $this->__wakeup();
            }

            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }

    /** @private */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    
    public function setColorCode($colorCode)
    {
        $this->__load();
        return parent::setColorCode($colorCode);
    }

    public function getColorCode()
    {
        $this->__load();
        return parent::getColorCode();
    }

    public function setAgeLimit($ageLimit)
    {
        $this->__load();
        return parent::setAgeLimit($ageLimit);
    }

    public function getAgeLimit()
    {
        $this->__load();
        return parent::getAgeLimit();
    }

    public function setStartAge($startAge)
    {
        $this->__load();
        return parent::setStartAge($startAge);
    }

    public function getStartAge()
    {
        $this->__load();
        return parent::getStartAge();
    }

    public function setEndAge($endAge)
    {
        $this->__load();
        return parent::setEndAge($endAge);
    }

    public function getEndAge()
    {
        $this->__load();
        return parent::getEndAge();
    }

    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int) $this->_identifier["id"];
        }
        $this->__load();
        return parent::getId();
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'colorCode', 'ageLimit', 'startAge', 'endAge', 'id');
    }

    public function __clone()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            $class = $this->_entityPersister->getClassMetadata();
            $original = $this->_entityPersister->load($this->_identifier);
            if ($original === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            foreach ($class->reflFields as $field => $reflProperty) {
                $reflProperty->setValue($this, $reflProperty->getValue($original));
            }
            unset($this->_entityPersister, $this->_identifier);
        }
        
    }
}